cidr: 127.0.11.0/24
contexts:
- name: my-context # empty for current-context
  cidr24:
  namespaces:
  - name: ns1
    services:
    - name: svc1
    - name: svc2
  - name: ns2
    services:
    - name: svc1
    - name: svc2