language: go
go:
- 1.16.x
script:
- GOOS=darwin  GOARCH=amd64 go build -o bin/fwd-osx-amd64
- GOOS=linux   GOARCH=amd64 go build -o bin/fwd-linux-amd64
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "e5jJ69dV0rQYSURDcQwbPbUa7CEKS7Uc+IkEPEs3zzBafFQEd79TLkoNLcfvmp8Xv3SCpdfwQLKC8sy1rthnsDdf2hTYDG+4GMFUYRwZr4spSTNsBOflEhrqwtCinoH5dcBkasdqjwKONTOgrMCuONrOI7kVw7bYnQpRmdH4e8eYIfBQBtsa4buzzXeQfSPQzTqXpezxS4uQ3P9kxJTSDqtqqOVgla3fhmAApzmMqfSXm5k1HM5IVMVu9J1oZBHL9Z+6shYhja2XPtlrT47AnvGrx5Y1lz5xqvMO6aab5zlpL4WOkNz+0DAK1epwF3dltmEE3X298/7tfaxXL/Q5Vk+iRjyZghBYs4CFGcXnMpo2oEeD9f9ASIVE+BBRhV0S0FDMe0Luh/eIBICPBxEiaDfz4lcs9wLH5OIlDdOWihQsw9yJ8lKzsU2RLw7i1qq+NXRsig87Rwc7ALfRYyW6WAO/GxuQuCwYZTkObgvEIyYpQaPB0Jsvly2ljJ5em7JqQOC5mYHQ4JSw6kB50hr0QOJ6jtADqn5hdFpKVz3+yfTxtbCEc8Ro0sBgg54L0np1S7rbIXcs2zNIpjRSBth8fWZhd0iESH6dJziC+IINAc/3Kofhyyeb7yfr+WoJ4feab58BnCF1C8f87L5yuC/3U7MAoUNZqctn0gZJOsdWP/s="
  file:
  - bin/fwd-osx-amd64
  - bin/fwd-linux-amd64
  on:
    repo: adamglt/fwd
    tags: true
